/**
 * Standard G3X Touch names for backplane instruments and publishers.
 */
export enum InstrumentBackplaneNames {
  Accelerometer = 'Accelerometer',
  Adc = 'Adc',
  Ahrs = 'Ahrs',
  Alert = 'Alert',
  Ambient = 'Ambient',
  Autopilot = 'Autopilot',
  AutopilotRadioNav = 'AutopilotRadioNav',
  Base = 'Base',
  Backlight = 'Backlight',
  Clock = 'Clock',
  ControlSurfaces = 'ControlSurfaces',
  Eis = 'Eis',
  Electrical = 'Electrical',
  Engine = 'Engine',
  FuelTotalizer = 'FuelTotalizer',
  GarminAutopilot = 'GarminAutopilot',
  G3XNav = 'G3XNav',
  Gnss = 'Gnss',
  HEvents = 'HEvents',
  LNavObs = 'LNavObs',
  Minimums = 'Minimums',
  NavCom = 'NavCom',
  NavComControl = 'NavComControl',
  NavEvents = 'NavEvents',
  NavProc = 'NavProc',
  Pressurization = 'Pressurization',
  Sound = 'Sound',
  Timer = 'Timer',
  Traffic = 'Traffic',
  VNav = 'VNav',
  WeightFuel = 'WeightFuel',
  Xpdr = 'Xpdr',
}
