/**
 * Standard G3000 names for backplane instruments and publishers.
 */
export enum InstrumentBackplaneNames {
  Adc = 'Adc',
  Ahrs = 'Ahrs',
  Alert = 'Alert',
  Ambient = 'Ambient',
  Autopilot = 'Autopilot',
  AutopilotRadioNav = 'AutopilotRadioNav',
  Backlight = 'Backlight',
  Base = 'Base',
  Clock = 'Clock',
  ControlSurfaces = 'ControlSurfaces',
  Eis = 'Eis',
  Electrical = 'Electrical',
  Engine = 'Engine',
  FuelTotalizer = 'FuelTotalizer',
  GarminAutopilot = 'GarminAutopilot',
  GarminNav = 'GarminNav',
  Gnss = 'Gnss',
  HEvents = 'HEvents',
  LNavObs = 'GarminObs',
  Minimums = 'Minimums',
  NavCom = 'NavCom',
  NavEvents = 'NavEvents',
  NavProc = 'NavProc',
  Pressurization = 'Pressurization',
  Sound = 'Sound',
  Timer = 'Timer',
  Traffic = 'Traffic',
  VNav = 'VNav',
  Xpdr = 'Xpdr',
}
