import { ICAO, UserFacility } from '@microsoft/msfs-sdk';


/**
 * Utilities for UNS-1 pilot defined waypoints
 */
export class UnsPilotWaypointUtils {
  /**
   * Returns the next available auto-generated name, given existing user facilities and an ident
   *
   * @param facilities the existing user facilities
   * @param ident      the ident of the facility
   *
   * @returns a string to be used as an ident for a user facility
   */
  public static nextAutoGeneratedName(facilities: UserFacility[], ident: string): string {
    let suffix = 1;

    for (const facility of facilities) {
      const facIdent = ICAO.getIdent(facility.icao);

      if (facIdent.match(`${ident.substring(0, 3)}\\d\\d`)) {
        suffix++;
      }
    }

    return `${ident.substring(0, 3)}${suffix.toString().padStart(2, '0')}`;
  }
}
