export enum GuiHEvent {
  UPPER_INC = 'UpperKnobInc',
  UPPER_DEC = 'UpperKnobDec',
  LOWER_INC = 'LowerKnobInc',
  LOWER_DEC = 'LowerKnobDec',
  UPPER_PUSH = 'UpperKnobPush',
  PFD_MENU_PUSH = 'PfdMenuPush',
  REFS_MENU_PUSH = 'RefsMenuPush',
  PFD_ESC = 'PfdEsc',
  UPR_MENU_PUSH = 'UpperMenuPush',
  LWR_MENU_PUSH = 'LowerMenuPush',
  MFD_ESC = 'MfdEsc',
  SOFTKEY_1L = 'Softkey1L',
  SOFTKEY_2L = 'Softkey2L',
  SOFTKEY_3L = 'Softkey3L',
  SOFTKEY_4L = 'Softkey4L',
  SOFTKEY_1R = 'Softkey1R',
  SOFTKEY_2R = 'Softkey2R',
  SOFTKEY_3R = 'Softkey3R',
  SOFTKEY_4R = 'Softkey4R',
}