/**
 * Utility class for working with ICAO region codes.
 */
export class Regions {
  private static readonly NAME_TABLE: Record<string, string> = {
    'AG': 'SOLOMON ISLANDS',
    'AN': 'NAURU',
    'AY': 'PAPUA NEW GUINEA',
    'BG': 'GREENLAND',
    'BI': 'ICELAND',
    'BK': 'KOSOVO',
    'CY': 'CANADA',
    'DA': 'ALGERIA',
    'DB': 'BENIN',
    'DF': 'BURKINA FASO',
    'DG': 'GHANA',
    'DI': 'IVORY COAST',
    'DN': 'NIGERIA',
    'DR': 'NIGER',
    'DT': 'TUNISIA',
    'DX': 'TOGO',
    'EB': 'BELGIUM',
    'ED': 'GERMANY',
    'EE': 'ESTONIA',
    'EF': 'FINLAND',
    'EG': 'UNITED KINGDOM',
    'EH': 'NETHERLANDS',
    'EI': 'IRELAND',
    'EK': 'DENMARK',
    'EL': 'LUXEMBOURG',
    'EN': 'NORWAY',
    'EP': 'POLAND',
    'ES': 'SWEDEN',
    'ET': 'GERMANY',
    'EV': 'LATVIA',
    'EY': 'LITHUANIA',
    'FA': 'SOUTH AFRICA',
    'FB': 'BOTSWANA',
    'FC': 'CONGO',
    'FD': 'ESWATINI',
    'FE': 'CENTRAL AFRICA',
    'FG': 'EQUITORIAL GUINEA',
    'FH': 'ASCENSION/ST HELENA',
    'FI': 'MAURITIUS',
    'FJ': 'INDIAN OCEAN TERRITORIES',
    'FK': 'CAMEROON',
    'FL': 'ZAMBIA',
    'FM': 'MADAGASCAR',
    'FN': 'ANGOLA',
    'FO': 'GABON',
    'FP': 'SAO TOME',
    'FQ': 'MOZAMBIQUE',
    'FS': 'SEYCHELLES',
    'FT': 'CHAD',
    'FV': 'ZIMBABWE',
    'FW': 'MALAWI',
    'FX': 'LESOTHO',
    'FY': 'NAMIBIA',
    'FZ': 'DEMOCRATIC REPUBLIC OF CONGO',
    'GA': 'MALI',
    'GB': 'GAMBIA',
    'GC': 'CANARY ISLANDS',
    'GE': 'MELILLA',
    'GF': 'SIERRA LEONE',
    'GG': 'GUINEA-BISSAU',
    'GL': 'LIBERIA',
    'GM': 'MOROCCO',
    'GO': 'SENEGAL',
    'GQ': 'MAURITANIA',
    'GS': 'WESTERN SAHARA',
    'GU': 'GUINEA',
    'GV': 'CAPE VERDE',
    'HA': 'ETHIOPIA',
    'HB': 'BURUNDI',
    'HD': 'DJIBOUTI',
    'HE': 'EGYPT',
    'HH': 'ERITREA',
    'HK': 'KENYA',
    'HL': 'LIBYA',
    'HR': 'RWANDA',
    'HS': 'SUDAN',
    'HT': 'TANZANIA',
    'HU': 'UGANDA',
    'K1': 'USA',
    'K2': 'USA',
    'K3': 'USA',
    'K4': 'USA',
    'K5': 'USA',
    'K6': 'USA',
    'K7': 'USA',
    'KA': 'USA',
    'KB': 'USA',
    'KC': 'USA',
    'KD': 'USA',
    'KE': 'USA',
    'KF': 'USA',
    'KG': 'USA',
    'KH': 'USA',
    'KI': 'USA',
    'KJ': 'USA',
    'KK': 'USA',
    'KL': 'USA',
    'KM': 'USA',
    'KN': 'USA',
    'KO': 'USA',
    'KP': 'USA',
    'KQ': 'USA',
    'KR': 'USA',
    'KS': 'USA',
    'KT': 'USA',
    'KU': 'USA',
    'KV': 'USA',
    'KW': 'USA',
    'KX': 'USA',
    'KY': 'USA',
    'KZ': 'USA',
    'LA': 'ALBANIA',
    'LB': 'BULGARIA',
    'LC': 'CYPRUS',
    'LD': 'CROATIA',
    'LE': 'SPAIN',
    'LF': 'FRANCE',
    'LG': 'GREECE',
    'LH': 'HUNGARY',
    'LI': 'ITALY',
    'LJ': 'SLOVENIA',
    'LK': 'CZECH',
    'LL': 'ISRAEL',
    'LM': 'MALTA',
    'LO': 'AUSTRIA',
    'LP': 'PORTUGAL',
    'LQ': 'BOSNIA-HERZGOVINIA',
    'LR': 'ROMANIA',
    'LS': 'SWITZERLAND',
    'LT': 'TURKEY',
    'LU': 'MOLDOVA',
    'LV': 'PALESTINE',
    'LW': 'MACEDONIA',
    'LX': 'GIBRALTAR',
    'LY': 'SERBIA/MONTENEGRO',
    'LZ': 'SLOVAKIA',
    'MB': 'TURKS AND CAICOS',
    'MD': 'DOMINICAN REPUBLIC',
    'MG': 'GUATEMALA',
    'MH': 'HONDURAS',
    'MK': 'JAMAICA',
    'MM': 'MEXICO',
    'MN': 'NICARAGUA',
    'MP': 'PANAMA',
    'MR': 'COSTA RICA',
    'MS': 'EL SALVADOR',
    'MT': 'HAITI',
    'MU': 'CUBA',
    'MW': 'CAYMAN ISLANDS',
    'MY': 'BAHAMAS',
    'MZ': 'BELIZE',
    'NC': 'COOK ISLANDS',
    'NF': 'FIJI/TONGA',
    'NG': 'KIRIBATI/TUVALU',
    'NI': 'NIUE',
    'NL': 'WALLIS AND FUTUNA',
    'NS': 'AMERICAN/WEST SAMOA',
    'NT': 'FRENCH POLYNESIA',
    'NV': 'VANUATU',
    'NW': 'NEW CALEDONIA',
    'NZ': 'NEW ZEALAND',
    'OA': 'AFGHANISTAN',
    'OB': 'BAHRAIN',
    'OE': 'SAUDI ARABIA',
    'OI': 'IRAN',
    'OJ': 'JORDAN',
    'OK': 'KUWAIT',
    'OL': 'LEBANON',
    'OM': 'UAE',
    'OO': 'OMAN',
    'OP': 'PAKISTAN',
    'OR': 'IRAQ',
    'OS': 'SYRIA',
    'OT': 'QATAR',
    'OY': 'YEMEN',
    'PA': 'USA',
    'PG': 'GUAM',
    'PH': 'USA',
    'PJ': 'JOHNSTON ATOLL',
    'PK': 'MARSHALL ISLANDS',
    'PL': 'KIRIBATI',
    'PM': 'MIDWAY ISLAND',
    'PO': 'USA',
    'PP': 'USA',
    'PT': 'MICRONESIA',
    'PW': 'WAKE ISLAND',
    'RC': 'TAIWAN',
    'RJ': 'JAPAN',
    'RK': 'SOUTH KOREA',
    'RO': 'JAPAN',
    'RP': 'PHILIPPINES',
    'SA': 'ARGENTINA',
    'SB': 'BRAZIL',
    'SC': 'CHILE',
    'SD': 'BRAZIL',
    'SE': 'ECUADOR',
    'SG': 'PARAGUAY',
    'SI': 'BRAZIL',
    'SJ': 'BRAZIL',
    'SK': 'COLOMBIA',
    'SL': 'BOLIVIA',
    'SM': 'SURINAME',
    'SO': 'FRENCH GUIANA',
    'SP': 'PERU',
    'SS': 'BRAZIL',
    'SU': 'URUGUAY',
    'SV': 'VENEZUELA',
    'SW': 'BRAZIL',
    'SY': 'GUYANA',
    'TA': 'ANTIGUA',
    'TB': 'BARBADOS',
    'TD': 'ANTIGUA',
    'TF': 'GUADELOUPE/MARTINIQUE',
    'TG': 'GRENADA',
    'TI': 'US VIRGIN ISLANDS',
    'TJ': 'PUERTO RICO',
    'TK': 'ST KITTS AND NEVIS',
    'TL': 'ST LUCIA',
    'TN': 'ARUBA',
    'TQ': 'ANGUILLA',
    'TT': 'MONTSERRAT',
    'TU': 'TRINIDAD AND TOBAGO',
    'TV': 'BRITISH VIRGIN ISLANDS',
    'TX': 'BERMUDA',
    'UA': 'KAZKHSTAN',
    'UB': 'AZERBAIJAN',
    'UC': 'KYRGYZSTAN',
    'UD': 'ARMENIA',
    'UE': 'RUSSIA',
    'UG': 'GEORGIA',
    'UH': 'RUSSIA',
    'UI': 'RUSSIA',
    'UK': 'UKRAINE',
    'UL': 'RUSSIA',
    'UM': 'RUSSIA/BELARUS',
    'UN': 'RUSSIA',
    'UO': 'RUSSIA',
    'UR': 'RUSSIA/KAZAKHSTAN',
    'US': 'RUSSIA',
    'UT': 'UZBEKISTAN/TAJIKISTAN',
    'UU': 'RUSSIA',
    'UW': 'RUSSIA',
    'VA': 'INDIA',
    'VC': 'SRI LANKA',
    'VD': 'CAMBODIA',
    'VE': 'INDIA',
    'VG': 'BANGLADESH',
    'VH': 'HONG KONG',
    'VI': 'INDIA',
    'VL': 'LAOS',
    'VM': 'MACAU',
    'VN': 'NEPAL',
    'VO': 'INDIA',
    'VR': 'MALDIVES',
    'VT': 'THAILAND',
    'VV': 'VIETNAM',
    'VY': 'MYANMAR',
    'WA': 'INDONESIA',
    'WB': 'BRUNEI',
    'WI': 'INDONESIA',
    'WM': 'MALAYSIA',
    'WR': 'INDONESIA',
    'WS': 'SINGAPORE',
    'YB': 'AUSTRALIA',
    'YM': 'AUSTRALIA',
    'ZB': 'CHINA',
    'ZG': 'CHINA',
    'ZH': 'CHINA',
    'ZK': 'NORTH KOREA',
    'ZL': 'CHINA',
    'ZM': 'MONGOLIA',
    'ZP': 'CHINA',
    'ZS': 'CHINA',
    'ZU': 'CHINA',
    'ZW': 'CHINA',
    'ZY': 'CHINA',
  };

  /**
   * Gets the display name of the region associated with a specified ICAO region code.
   * @param code - the 2 character ICAO region code.
   * @returns the display name of the region.
   */
  public static getName(code: string): string {
    const name = Regions.NAME_TABLE[code.toUpperCase()];
    return name ?? '';
  }
}
