export enum BtnImagePathHor {
  BackspaceIcon = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/backspace.png',
  ButtonRoundDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/btn-round-down.png',
  ButtonRoundUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/btn-round-up.png',
  ComBottomBorder = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/com-bottom-border.png',
  ComBottomDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/com-bottom-down.png',
  ComBottomHighlight = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/com-bottom-highlight.png',
  ComBottomUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/com-bottom-up.png',
  ComTopDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/com-top-down.png',
  ComTopUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/com-top-up.png',
  DoubleArrow = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/double-arrow.png',
  FindIcon = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/find.png',
  MicDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/mic-down.png',
  MicUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/mic-up.png',
  MonDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/mon-down.png',
  MonUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/mon-up.png',
  PlayIcon = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/play.png',
  TriangleDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/mic-mon-triangle-down.png',
  TriangleUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/mic-mon-triangle-up.png',
  XpdrBottomDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/xpdr-bottom-down.png',
  XpdrBottomUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/xpdr-bottom-up.png',
  XpdrTopDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/xpdr-top-down.png',
  XpdrTopUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/horizontal/xpdr-top-up.png',
}

export enum BtnImagePathVert {
  ButtonRoundSmallDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/btn-round-small-down.png',
  ButtonRoundSmallUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/btn-round-small-up.png',
  ComBottomBorder = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/com-bottom-border.png',
  ComBottomDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/com-bottom-down.png',
  ComBottomHighlight = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/com-bottom-highlight-small.png',
  ComBottomUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/com-bottom-up.png',
  ComTopDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/com-top-down.png',
  ComTopUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/com-top-up.png',
  MicDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/mic-down-small.png',
  MicUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/mic-up-small.png',
  MonDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/mon-down-small.png',
  MonUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/mon-up-small.png',
  TrafficDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/traffic-down.png',
  TrafficUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/traffic-up.png',
  TriangleLeft = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/icon_mic_mon_arrow_left.png',
  TriangleRight = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/icon_mic_mon_arrow_right.png',
  XpdrBottomDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/xpdr-bottom-down.png',
  XpdrBottomUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/xpdr-bottom-up.png',
  XpdrTopDown = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/xpdr-top-down.png',
  XpdrTopUp = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/buttons/vertical/xpdr-top-up.png',
}

export enum BtnImagePath {
  PlaybackBackward = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_playback_backward.png',
  PlaybackForward = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_playback_forward.png',
  SoftKeyArrowActive = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_knob_pair_arrow_active.png',
  SoftKeyArrowInactive = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_knob_pair_arrow_inactive.png',
  TrafficMap = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_traffic_map_home.png',
  WaypointFilterAll = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_small_waypoint_info.png',
  WaypointFilterAirport = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_small_airport.png',
  WaypointFilterIntersection = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_small_intersection.png',
  WaypointFilterNdb = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_small_ndb.png',
  WaypointFilterVor = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_small_vor.png',
  WaypointFilterUser = '/Pages/VCockpit/Instruments/NavSystems/WTG3000/Assets/Images/GTC/icon_small_user.png',
}